-- AutoServiceHub - Initial schema + RLS policies
-- Run in Supabase SQL Editor, or use Supabase CLI migrations.
-- Requires: auth.users (built-in)

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  name text unique not null
);

create table if not exists public.user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role_id bigint not null references public.roles(id) on delete restrict,
  created_at timestamptz not null default now()
);

create table if not exists public.service_requests (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  car_model text not null,
  description text not null,
  status text not null default 'new' check (status in ('new','in_progress','done','rejected')),
  created_at timestamptz not null default now()
);

create table if not exists public.request_files (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.service_requests(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  file_path text not null,
  original_name text not null,
  created_at timestamptz not null default now()
);

-- Seed roles
insert into public.roles(name) values ('user')
  on conflict (name) do nothing;
insert into public.roles(name) values ('admin')
  on conflict (name) do nothing;

-- Helper function: check if current user is admin
create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid() and r.name = 'admin'
  );
$$;

-- Trigger: create profile for new users
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', new.email))
  on conflict (id) do nothing;

  -- default role "user"
  insert into public.user_roles(user_id, role_id)
  select new.id, r.id from public.roles r where r.name='user'
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- RLS
alter table public.profiles enable row level security;
alter table public.roles enable row level security;
alter table public.user_roles enable row level security;
alter table public.service_requests enable row level security;
alter table public.request_files enable row level security;

-- profiles: user can read own; update own
drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
  for select using (auth.uid() = id or public.is_admin());

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
  for update using (auth.uid() = id or public.is_admin())
  with check (auth.uid() = id or public.is_admin());

-- roles: readable only for admins (optional)
drop policy if exists "roles_select_admin" on public.roles;
create policy "roles_select_admin" on public.roles
  for select using (public.is_admin());

-- user_roles: admins can manage; users can read their own
drop policy if exists "user_roles_select_own" on public.user_roles;
create policy "user_roles_select_own" on public.user_roles
  for select using (auth.uid() = user_id or public.is_admin());

drop policy if exists "user_roles_manage_admin" on public.user_roles;
create policy "user_roles_manage_admin" on public.user_roles
  for all using (public.is_admin()) with check (public.is_admin());

-- service_requests: users manage own; admin manage all
drop policy if exists "requests_select" on public.service_requests;
create policy "requests_select" on public.service_requests
  for select using (auth.uid() = owner_id or public.is_admin());

drop policy if exists "requests_insert" on public.service_requests;
create policy "requests_insert" on public.service_requests
  for insert with check (auth.uid() = owner_id);

drop policy if exists "requests_update" on public.service_requests;
create policy "requests_update" on public.service_requests
  for update using (auth.uid() = owner_id or public.is_admin())
  with check (auth.uid() = owner_id or public.is_admin());

drop policy if exists "requests_delete" on public.service_requests;
create policy "requests_delete" on public.service_requests
  for delete using (auth.uid() = owner_id or public.is_admin());

-- request_files: users manage own; admin all
drop policy if exists "files_select" on public.request_files;
create policy "files_select" on public.request_files
  for select using (auth.uid() = owner_id or public.is_admin());

drop policy if exists "files_insert" on public.request_files;
create policy "files_insert" on public.request_files
  for insert with check (auth.uid() = owner_id);

drop policy if exists "files_delete" on public.request_files;
create policy "files_delete" on public.request_files
  for delete using (auth.uid() = owner_id or public.is_admin());
